name: My First GitHub Action
on: [push]
jobs :
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22.12.0'
      - run: npm install
      - run: npm run build
      - run: tree