name: My First GitHub Action
on: [push]
jobs :
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22.12.0'
      - name: Build the Project
        run: npm install
      - name: Setup Finish
        run: echo "Setup Finish Hurrayyy!!!!"